name: Package for NPM

on:
  workflow_dispatch:

jobs:
  package:
    name: Package
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Set Swift Version
        run:
          cp priv/WebSocketDist/.swift-version .swift-version

      - name: Install Swift
        uses: ./.github/actions/install-swift

      - name: Build
        working-directory: priv/WebSocketDist/package
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-socket-dist
          path: priv/WebSocketDist/package